# TCL File Generated by Component Editor 19.1
# Sat Dec 07 21:53:19 CET 2019
# DO NOT MODIFY


# 
# fejkon_pcie_avalon "Fejkon PCIe Avalon Master" v1.0
#  2019.12.07.21:53:19
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module fejkon_pcie_avalon
# 
set_module_property DESCRIPTION ""
set_module_property NAME fejkon_pcie_avalon
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Fejkon PCIe Avalon Master"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL fejkon_pcie_avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file fejkon_pcie_avalon.sv SYSTEM_VERILOG PATH fejkon_pcie_avalon.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point mem_access_resp
# 
add_interface mem_access_resp avalon_streaming start
set_interface_property mem_access_resp associatedClock clk
set_interface_property mem_access_resp associatedReset reset
set_interface_property mem_access_resp dataBitsPerSymbol 128
set_interface_property mem_access_resp errorDescriptor ""
set_interface_property mem_access_resp firstSymbolInHighOrderBits true
set_interface_property mem_access_resp maxChannel 0
set_interface_property mem_access_resp readyLatency 0
set_interface_property mem_access_resp ENABLED true
set_interface_property mem_access_resp EXPORT_OF ""
set_interface_property mem_access_resp PORT_NAME_MAP ""
set_interface_property mem_access_resp CMSIS_SVD_VARIABLES ""
set_interface_property mem_access_resp SVD_ADDRESS_GROUP ""

add_interface_port mem_access_resp mem_access_resp_data data Output 128
add_interface_port mem_access_resp mem_access_resp_ready ready Input 1
add_interface_port mem_access_resp mem_access_resp_valid valid Output 1


# 
# connection point mem_access_req
# 
add_interface mem_access_req avalon_streaming end
set_interface_property mem_access_req associatedClock clk
set_interface_property mem_access_req associatedReset reset
set_interface_property mem_access_req dataBitsPerSymbol 128
set_interface_property mem_access_req errorDescriptor ""
set_interface_property mem_access_req firstSymbolInHighOrderBits true
set_interface_property mem_access_req maxChannel 0
set_interface_property mem_access_req readyLatency 0
set_interface_property mem_access_req ENABLED true
set_interface_property mem_access_req EXPORT_OF ""
set_interface_property mem_access_req PORT_NAME_MAP ""
set_interface_property mem_access_req CMSIS_SVD_VARIABLES ""
set_interface_property mem_access_req SVD_ADDRESS_GROUP ""

add_interface_port mem_access_req mem_access_req_data data Input 128
add_interface_port mem_access_req mem_access_req_ready ready Output 1
add_interface_port mem_access_req mem_access_req_valid valid Input 1


# 
# connection point mm
# 
add_interface mm avalon start
set_interface_property mm addressUnits SYMBOLS
set_interface_property mm associatedClock clk
set_interface_property mm associatedReset reset
set_interface_property mm bitsPerSymbol 8
set_interface_property mm burstOnBurstBoundariesOnly false
set_interface_property mm burstcountUnits WORDS
set_interface_property mm doStreamReads false
set_interface_property mm doStreamWrites false
set_interface_property mm holdTime 0
set_interface_property mm linewrapBursts false
set_interface_property mm maximumPendingReadTransactions 0
set_interface_property mm maximumPendingWriteTransactions 0
set_interface_property mm readLatency 0
set_interface_property mm readWaitTime 1
set_interface_property mm setupTime 0
set_interface_property mm timingUnits Cycles
set_interface_property mm writeWaitTime 0
set_interface_property mm ENABLED true
set_interface_property mm EXPORT_OF ""
set_interface_property mm PORT_NAME_MAP ""
set_interface_property mm CMSIS_SVD_VARIABLES ""
set_interface_property mm SVD_ADDRESS_GROUP ""

add_interface_port mm mm_address address Output 32
add_interface_port mm mm_byteenable byteenable Output 4
add_interface_port mm mm_read read Output 1
add_interface_port mm mm_readdata readdata Input 32
add_interface_port mm mm_readdatavalid readdatavalid Input 1
add_interface_port mm mm_write write Output 1
add_interface_port mm mm_waitrequest waitrequest Input 1
add_interface_port mm mm_writedata writedata Output 32
add_interface_port mm mm_writeresponsevalid writeresponsevalid Input 1
add_interface_port mm mm_response response Input 2


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1

