# TCL File Generated by Component Editor 19.1
# Fri Nov 01 20:32:53 CET 2019
# DO NOT MODIFY


# 
# fejkon_led "Fejkon LED Driver" v1.0
# bluecmd 2019.11.01.20:32:53
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module fejkon_led
# 
set_module_property DESCRIPTION ""
set_module_property NAME fejkon_led
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR bluecmd
set_module_property DISPLAY_NAME "Fejkon LED Driver"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL fejkon_led
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file fejkon_led.sv SYSTEM_VERILOG PATH fejkon_led.sv TOP_LEVEL_FILE
add_fileset_file flap_detect.sv SYSTEM_VERILOG PATH flap_detect.sv
add_fileset_file fejkon_led.sdc SDC PATH fejkon_led.sdc

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL fejkon_led
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file fejkon_led.sv SYSTEM_VERILOG PATH fejkon_led.sv
add_fileset_file flap_detect.sv SYSTEM_VERILOG PATH flap_detect.sv


# 
# parameters
# 
add_parameter ReferenceClock POSITIVE 50000000 ""
set_parameter_property ReferenceClock DEFAULT_VALUE 50000000
set_parameter_property ReferenceClock DISPLAY_NAME ReferenceClock
set_parameter_property ReferenceClock TYPE POSITIVE
set_parameter_property ReferenceClock VISIBLE false
set_parameter_property ReferenceClock UNITS Hertz
set_parameter_property ReferenceClock ALLOWED_RANGES 1:2147483647
set_parameter_property ReferenceClock DESCRIPTION ""
set_parameter_property ReferenceClock AFFECTS_GENERATION false
set_parameter_property ReferenceClock HDL_PARAMETER true
set_parameter_property ReferenceClock SYSTEM_INFO_TYPE CLOCK_RATE
set_parameter_property ReferenceClock SYSTEM_INFO_ARG clk


# 
# display items
# 


# 
# connection point ref_clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point fcport0_active
# 
add_interface fcport0_active conduit end
set_interface_property fcport0_active associatedClock ""
set_interface_property fcport0_active associatedReset ""
set_interface_property fcport0_active ENABLED true
set_interface_property fcport0_active EXPORT_OF ""
set_interface_property fcport0_active PORT_NAME_MAP ""
set_interface_property fcport0_active CMSIS_SVD_VARIABLES ""
set_interface_property fcport0_active SVD_ADDRESS_GROUP ""

add_interface_port fcport0_active fcport0_active active Input 1


# 
# connection point fcport0_aligned
# 
add_interface fcport0_aligned conduit end
set_interface_property fcport0_aligned associatedClock ""
set_interface_property fcport0_aligned associatedReset ""
set_interface_property fcport0_aligned ENABLED true
set_interface_property fcport0_aligned EXPORT_OF ""
set_interface_property fcport0_aligned PORT_NAME_MAP ""
set_interface_property fcport0_aligned CMSIS_SVD_VARIABLES ""
set_interface_property fcport0_aligned SVD_ADDRESS_GROUP ""

add_interface_port fcport0_aligned fcport0_aligned aligned Input 1


# 
# connection point fcport1_active
# 
add_interface fcport1_active conduit end
set_interface_property fcport1_active associatedClock ""
set_interface_property fcport1_active associatedReset ""
set_interface_property fcport1_active ENABLED true
set_interface_property fcport1_active EXPORT_OF ""
set_interface_property fcport1_active PORT_NAME_MAP ""
set_interface_property fcport1_active CMSIS_SVD_VARIABLES ""
set_interface_property fcport1_active SVD_ADDRESS_GROUP ""

add_interface_port fcport1_active fcport1_active active Input 1


# 
# connection point fcport1_aligned
# 
add_interface fcport1_aligned conduit end
set_interface_property fcport1_aligned associatedClock ""
set_interface_property fcport1_aligned associatedReset ""
set_interface_property fcport1_aligned ENABLED true
set_interface_property fcport1_aligned EXPORT_OF ""
set_interface_property fcport1_aligned PORT_NAME_MAP ""
set_interface_property fcport1_aligned CMSIS_SVD_VARIABLES ""
set_interface_property fcport1_aligned SVD_ADDRESS_GROUP ""

add_interface_port fcport1_aligned fcport1_aligned aligned Input 1


# 
# connection point fcport2_active
# 
add_interface fcport2_active conduit end
set_interface_property fcport2_active associatedClock ""
set_interface_property fcport2_active associatedReset ""
set_interface_property fcport2_active ENABLED true
set_interface_property fcport2_active EXPORT_OF ""
set_interface_property fcport2_active PORT_NAME_MAP ""
set_interface_property fcport2_active CMSIS_SVD_VARIABLES ""
set_interface_property fcport2_active SVD_ADDRESS_GROUP ""

add_interface_port fcport2_active fcport2_active active Input 1


# 
# connection point fcport2_aligned
# 
add_interface fcport2_aligned conduit end
set_interface_property fcport2_aligned associatedClock ""
set_interface_property fcport2_aligned associatedReset ""
set_interface_property fcport2_aligned ENABLED true
set_interface_property fcport2_aligned EXPORT_OF ""
set_interface_property fcport2_aligned PORT_NAME_MAP ""
set_interface_property fcport2_aligned CMSIS_SVD_VARIABLES ""
set_interface_property fcport2_aligned SVD_ADDRESS_GROUP ""

add_interface_port fcport2_aligned fcport2_aligned aligned Input 1


# 
# connection point fcport3_active
# 
add_interface fcport3_active conduit end
set_interface_property fcport3_active associatedClock ""
set_interface_property fcport3_active associatedReset ""
set_interface_property fcport3_active ENABLED true
set_interface_property fcport3_active EXPORT_OF ""
set_interface_property fcport3_active PORT_NAME_MAP ""
set_interface_property fcport3_active CMSIS_SVD_VARIABLES ""
set_interface_property fcport3_active SVD_ADDRESS_GROUP ""

add_interface_port fcport3_active fcport3_active active Input 1


# 
# connection point fcport3_aligned
# 
add_interface fcport3_aligned conduit end
set_interface_property fcport3_aligned associatedClock ""
set_interface_property fcport3_aligned associatedReset ""
set_interface_property fcport3_aligned ENABLED true
set_interface_property fcport3_aligned EXPORT_OF ""
set_interface_property fcport3_aligned PORT_NAME_MAP ""
set_interface_property fcport3_aligned CMSIS_SVD_VARIABLES ""
set_interface_property fcport3_aligned SVD_ADDRESS_GROUP ""

add_interface_port fcport3_aligned fcport3_aligned aligned Input 1


# 
# connection point xcvr_reconfig
# 
add_interface xcvr_reconfig conduit end
set_interface_property xcvr_reconfig associatedClock ""
set_interface_property xcvr_reconfig associatedReset ""
set_interface_property xcvr_reconfig ENABLED true
set_interface_property xcvr_reconfig EXPORT_OF ""
set_interface_property xcvr_reconfig PORT_NAME_MAP ""
set_interface_property xcvr_reconfig CMSIS_SVD_VARIABLES ""
set_interface_property xcvr_reconfig SVD_ADDRESS_GROUP ""

add_interface_port xcvr_reconfig reconfig_busy reconfig_busy Input 1


# 
# connection point led
# 
add_interface led conduit end
set_interface_property led associatedClock ""
set_interface_property led associatedReset ""
set_interface_property led ENABLED true
set_interface_property led EXPORT_OF ""
set_interface_property led PORT_NAME_MAP ""
set_interface_property led CMSIS_SVD_VARIABLES ""
set_interface_property led SVD_ADDRESS_GROUP ""

add_interface_port led led_bracket bracket Output 4
add_interface_port led led_rj45 rj45 Output 2
add_interface_port led led_board board Output 4

