# TCL File Generated by Component Editor 19.1
# Sun Oct 20 12:32:45 CEST 2019
# DO NOT MODIFY


# 
# intel_temp "FPGA Temperature MM" v1.0
# bluecmd 2019.10.20.12:32:45
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module intel_temp
# 
set_module_property DESCRIPTION ""
set_module_property NAME intel_temp
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR bluecmd
set_module_property DISPLAY_NAME "FPGA Temperature MM"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL intel_temp
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file intel_temp.sv SYSTEM_VERILOG PATH intel_temp.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL intel_temp
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file intel_temp.sv SYSTEM_VERILOG PATH intel_temp.sv


# 
# parameters
# 
add_parameter FanTemp POSITIVE 1 ""
set_parameter_property FanTemp DEFAULT_VALUE 70
set_parameter_property FanTemp DISPLAY_NAME "Fan threshold (Celsius)"
set_parameter_property FanTemp WIDTH ""
set_parameter_property FanTemp TYPE INTEGER
set_parameter_property FanTemp UNITS None
set_parameter_property FanTemp ALLOWED_RANGES -128:127
set_parameter_property FanTemp DESCRIPTION ""
set_parameter_property FanTemp AFFECTS_GENERATION false
set_parameter_property FanTemp HDL_PARAMETER true

add_parameter FanOut POSITIVE 1 ""
set_parameter_property FanOut DEFAULT_VALUE true
set_parameter_property FanOut DISPLAY_NAME "Fan control output (active high)"
set_parameter_property FanOut WIDTH ""
set_parameter_property FanOut TYPE BOOLEAN
set_parameter_property FanOut UNITS None
set_parameter_property FanOut DESCRIPTION ""
set_parameter_property FanOut AFFECTS_ELABORATION true
set_parameter_property FanOut HDL_PARAMETER false

add_parameter FanInvOut POSITIVE 1 ""
set_parameter_property FanInvOut DEFAULT_VALUE false
set_parameter_property FanInvOut DISPLAY_NAME "Fan control output (active low)"
set_parameter_property FanInvOut WIDTH ""
set_parameter_property FanInvOut TYPE BOOLEAN
set_parameter_property FanInvOut UNITS None
set_parameter_property FanInvOut DESCRIPTION ""
set_parameter_property FanInvOut AFFECTS_ELABORATION true
set_parameter_property FanInvOut HDL_PARAMETER false

proc elaborate {} {
  if {[get_parameter_value FanOut] == "true"} {
    set_interface_property fan ENABLED true
  }
  if {[get_parameter_value FanInvOut] == "true"} {
    set_interface_property fan_n ENABLED true
  }
}

set_module_property ELABORATION_CALLBACK elaborate


# 
# display items
# 


# 
# connection point temp_mm
# 
add_interface temp_mm avalon end
set_interface_property temp_mm addressUnits WORDS
set_interface_property temp_mm associatedClock clk
set_interface_property temp_mm associatedReset reset
set_interface_property temp_mm bitsPerSymbol 8
set_interface_property temp_mm burstOnBurstBoundariesOnly false
set_interface_property temp_mm burstcountUnits WORDS
set_interface_property temp_mm explicitAddressSpan 0
set_interface_property temp_mm holdTime 0
set_interface_property temp_mm linewrapBursts false
set_interface_property temp_mm maximumPendingReadTransactions 0
set_interface_property temp_mm maximumPendingWriteTransactions 0
set_interface_property temp_mm readLatency 0
set_interface_property temp_mm readWaitTime 1
set_interface_property temp_mm setupTime 0
set_interface_property temp_mm timingUnits Cycles
set_interface_property temp_mm writeWaitTime 0
set_interface_property temp_mm ENABLED true
set_interface_property temp_mm EXPORT_OF ""
set_interface_property temp_mm PORT_NAME_MAP ""
set_interface_property temp_mm CMSIS_SVD_VARIABLES ""
set_interface_property temp_mm SVD_ADDRESS_GROUP ""

add_interface_port temp_mm temp_mm_readdata readdata Output 16
set_interface_assignment temp_mm embeddedsw.configuration.isFlash 0
set_interface_assignment temp_mm embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment temp_mm embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment temp_mm embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point tsdcalo
# 
add_interface tsdcalo conduit end
set_interface_property tsdcalo associatedClock ""
set_interface_property tsdcalo associatedReset ""
set_interface_property tsdcalo ENABLED true
set_interface_property tsdcalo EXPORT_OF ""
set_interface_property tsdcalo PORT_NAME_MAP ""
set_interface_property tsdcalo CMSIS_SVD_VARIABLES ""
set_interface_property tsdcalo SVD_ADDRESS_GROUP ""

add_interface_port tsdcalo tsdcalo tsdcalo Input 8


# 
# connection point tsdcaldone
# 
add_interface tsdcaldone conduit end
set_interface_property tsdcaldone associatedClock ""
set_interface_property tsdcaldone associatedReset ""
set_interface_property tsdcaldone ENABLED true
set_interface_property tsdcaldone EXPORT_OF ""
set_interface_property tsdcaldone PORT_NAME_MAP ""
set_interface_property tsdcaldone CMSIS_SVD_VARIABLES ""
set_interface_property tsdcaldone SVD_ADDRESS_GROUP ""

add_interface_port tsdcaldone tsdcaldone tsdcaldone Input 1


# 
# connection point clr
# 
add_interface clr reset start
set_interface_property clr associatedClock clk
set_interface_property clr associatedDirectReset ""
set_interface_property clr associatedResetSinks reset
set_interface_property clr synchronousEdges BOTH
set_interface_property clr ENABLED true
set_interface_property clr EXPORT_OF ""
set_interface_property clr PORT_NAME_MAP ""
set_interface_property clr CMSIS_SVD_VARIABLES ""
set_interface_property clr SVD_ADDRESS_GROUP ""

add_interface_port clr clr reset Output 1

# 
# connection point fan
# 
add_interface fan conduit end
set_interface_property fan associatedClock clk
set_interface_property fan associatedReset reset
set_interface_property fan ENABLED false
set_interface_property fan EXPORT_OF ""
set_interface_property fan PORT_NAME_MAP ""
set_interface_property fan CMSIS_SVD_VARIABLES ""
set_interface_property fan SVD_ADDRESS_GROUP ""

add_interface_port fan fan fan Output 1

# 
# connection point fan_n
# 
add_interface fan_n conduit end
set_interface_property fan_n associatedClock clk
set_interface_property fan_n associatedReset reset
set_interface_property fan_n ENABLED false
set_interface_property fan_n EXPORT_OF ""
set_interface_property fan_n PORT_NAME_MAP ""
set_interface_property fan_n CMSIS_SVD_VARIABLES ""
set_interface_property fan_n SVD_ADDRESS_GROUP ""

add_interface_port fan_n fan_n fan_n Output 1

