# TCL File Generated by Component Editor 20.1
# Sun Sep 13 17:52:24 CEST 2020
# DO NOT MODIFY


# 
# stream_capture "Stream Capture" v1.0
#  2020.09.13.17:52:24
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module stream_capture
# 
set_module_property DESCRIPTION ""
set_module_property NAME stream_capture
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Stream Capture"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL stream_capture
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file stream_capture.sv SYSTEM_VERILOG PATH stream_capture.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL stream_capture
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file stream_capture.sv SYSTEM_VERILOG PATH stream_capture.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point port0_mem
# 
add_interface port0_mem avalon start
set_interface_property port0_mem addressUnits SYMBOLS
set_interface_property port0_mem associatedClock clk
set_interface_property port0_mem associatedReset reset
set_interface_property port0_mem bitsPerSymbol 8
set_interface_property port0_mem burstOnBurstBoundariesOnly false
set_interface_property port0_mem burstcountUnits WORDS
set_interface_property port0_mem doStreamReads false
set_interface_property port0_mem doStreamWrites false
set_interface_property port0_mem holdTime 0
set_interface_property port0_mem linewrapBursts false
set_interface_property port0_mem maximumPendingReadTransactions 0
set_interface_property port0_mem maximumPendingWriteTransactions 0
set_interface_property port0_mem readLatency 0
set_interface_property port0_mem readWaitTime 0
set_interface_property port0_mem setupTime 0
set_interface_property port0_mem timingUnits Cycles
set_interface_property port0_mem writeWaitTime 0
set_interface_property port0_mem ENABLED true
set_interface_property port0_mem EXPORT_OF ""
set_interface_property port0_mem PORT_NAME_MAP ""
set_interface_property port0_mem CMSIS_SVD_VARIABLES ""
set_interface_property port0_mem SVD_ADDRESS_GROUP ""

add_interface_port port0_mem port0_mem_address address Output 20
add_interface_port port0_mem port0_mem_writedata writedata Output 64
add_interface_port port0_mem port0_mem_write write Output 1


# 
# connection point csr
# 
add_interface csr avalon end
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock clk
set_interface_property csr associatedReset reset
set_interface_property csr bitsPerSymbol 8
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 0
set_interface_property csr maximumPendingWriteTransactions 0
set_interface_property csr readLatency 0
set_interface_property csr readWaitTime 1
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""

add_interface_port csr csr_address address Input 4
add_interface_port csr csr_write write Input 1
add_interface_port csr csr_read read Input 1
add_interface_port csr csr_writedata writedata Input 32
add_interface_port csr csr_readdata readdata Output 32
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0


# 
# connection point port1_mem
# 
add_interface port1_mem avalon start
set_interface_property port1_mem addressUnits SYMBOLS
set_interface_property port1_mem associatedClock clk
set_interface_property port1_mem associatedReset reset
set_interface_property port1_mem bitsPerSymbol 8
set_interface_property port1_mem burstOnBurstBoundariesOnly false
set_interface_property port1_mem burstcountUnits WORDS
set_interface_property port1_mem doStreamReads false
set_interface_property port1_mem doStreamWrites false
set_interface_property port1_mem holdTime 0
set_interface_property port1_mem linewrapBursts false
set_interface_property port1_mem maximumPendingReadTransactions 0
set_interface_property port1_mem maximumPendingWriteTransactions 0
set_interface_property port1_mem readLatency 0
set_interface_property port1_mem readWaitTime 0
set_interface_property port1_mem setupTime 0
set_interface_property port1_mem timingUnits Cycles
set_interface_property port1_mem writeWaitTime 0
set_interface_property port1_mem ENABLED true
set_interface_property port1_mem EXPORT_OF ""
set_interface_property port1_mem PORT_NAME_MAP ""
set_interface_property port1_mem CMSIS_SVD_VARIABLES ""
set_interface_property port1_mem SVD_ADDRESS_GROUP ""

add_interface_port port1_mem port1_mem_address address Output 20
add_interface_port port1_mem port1_mem_write write Output 1
add_interface_port port1_mem port1_mem_writedata writedata Output 64


# 
# connection point port0_st
# 
add_interface port0_st avalon_streaming end
set_interface_property port0_st associatedClock clk
set_interface_property port0_st associatedReset reset
set_interface_property port0_st dataBitsPerSymbol 9
set_interface_property port0_st errorDescriptor ""
set_interface_property port0_st firstSymbolInHighOrderBits true
set_interface_property port0_st maxChannel 0
set_interface_property port0_st readyLatency 0
set_interface_property port0_st ENABLED true
set_interface_property port0_st EXPORT_OF ""
set_interface_property port0_st PORT_NAME_MAP ""
set_interface_property port0_st CMSIS_SVD_VARIABLES ""
set_interface_property port0_st SVD_ADDRESS_GROUP ""

add_interface_port port0_st port0_st_data data Input 36
add_interface_port port0_st port0_st_valid valid Input 1


# 
# connection point port1_st
# 
add_interface port1_st avalon_streaming end
set_interface_property port1_st associatedClock clk
set_interface_property port1_st associatedReset reset
set_interface_property port1_st dataBitsPerSymbol 9
set_interface_property port1_st errorDescriptor ""
set_interface_property port1_st firstSymbolInHighOrderBits true
set_interface_property port1_st maxChannel 0
set_interface_property port1_st readyLatency 0
set_interface_property port1_st ENABLED true
set_interface_property port1_st EXPORT_OF ""
set_interface_property port1_st PORT_NAME_MAP ""
set_interface_property port1_st CMSIS_SVD_VARIABLES ""
set_interface_property port1_st SVD_ADDRESS_GROUP ""

add_interface_port port1_st port1_st_data data Input 36
add_interface_port port1_st port1_st_valid valid Input 1


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point snoop_reset
# 
add_interface snoop_reset reset start
set_interface_property snoop_reset associatedClock clk
set_interface_property snoop_reset associatedDirectReset ""
set_interface_property snoop_reset associatedResetSinks reset
set_interface_property snoop_reset synchronousEdges DEASSERT
set_interface_property snoop_reset ENABLED true
set_interface_property snoop_reset EXPORT_OF ""
set_interface_property snoop_reset PORT_NAME_MAP ""
set_interface_property snoop_reset CMSIS_SVD_VARIABLES ""
set_interface_property snoop_reset SVD_ADDRESS_GROUP ""

add_interface_port snoop_reset snoop_reset reset Output 1

