# TCL File Generated by Component Editor 20.1
# Sat Sep 26 20:14:22 CEST 2020
# DO NOT MODIFY


#
# av_st_fixed_mux "Avalon-ST Fixed Multiplexer" v1.0
#  2020.09.26.20:14:22
#
#

#
# request TCL package from ACDS 16.1
#
package require -exact qsys 16.1


#
# module av_st_fixed_mux
#
set_module_property DESCRIPTION ""
set_module_property NAME av_st_fixed_mux
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR bluecmd
set_module_property DISPLAY_NAME "Avalon-ST Fixed Multiplexer"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


#
# file sets
#
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL av_st_fixed_mux
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file av_st_fixed_mux.sv SYSTEM_VERILOG PATH av_st_fixed_mux.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL av_st_fixed_mux
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file av_st_fixed_mux.sv SYSTEM_VERILOG PATH av_st_fixed_mux.sv


#
# parameters
#
add_parameter SelectedPort POSITIVE 1 ""
set_parameter_property SelectedPort DEFAULT_VALUE 0
set_parameter_property SelectedPort DISPLAY_NAME "Selected port"
set_parameter_property SelectedPort WIDTH ""
set_parameter_property SelectedPort TYPE INTEGER
set_parameter_property SelectedPort UNITS None
set_parameter_property SelectedPort ALLOWED_RANGES 0:1
set_parameter_property SelectedPort DESCRIPTION ""
set_parameter_property SelectedPort AFFECTS_GENERATION false
set_parameter_property SelectedPort HDL_PARAMETER true

add_parameter BitsPerSymbol POSITIVE 1 ""
set_parameter_property BitsPerSymbol DEFAULT_VALUE 8
set_parameter_property BitsPerSymbol DISPLAY_NAME "Bits per symbol"
set_parameter_property BitsPerSymbol WIDTH ""
set_parameter_property BitsPerSymbol TYPE INTEGER
set_parameter_property BitsPerSymbol UNITS BITS
set_parameter_property BitsPerSymbol ALLOWED_RANGES 1:128
set_parameter_property BitsPerSymbol DESCRIPTION ""
set_parameter_property BitsPerSymbol AFFECTS_GENERATION false
set_parameter_property BitsPerSymbol HDL_PARAMETER true

add_parameter SymbolsPerBeat POSITIVE 1 ""
set_parameter_property SymbolsPerBeat DEFAULT_VALUE 4
set_parameter_property SymbolsPerBeat DISPLAY_NAME "Symbols per beat"
set_parameter_property SymbolsPerBeat WIDTH ""
set_parameter_property SymbolsPerBeat TYPE INTEGER
set_parameter_property SymbolsPerBeat UNITS None
set_parameter_property SymbolsPerBeat ALLOWED_RANGES 1:128
set_parameter_property SymbolsPerBeat DESCRIPTION ""
set_parameter_property SymbolsPerBeat AFFECTS_GENERATION false
set_parameter_property SymbolsPerBeat HDL_PARAMETER true

add_parameter AvChannel POSITIVE 1 ""
set_parameter_property AvChannel DEFAULT_VALUE false
set_parameter_property AvChannel DISPLAY_NAME "Use channels"
set_parameter_property AvChannel WIDTH ""
set_parameter_property AvChannel TYPE BOOLEAN
set_parameter_property AvChannel UNITS None
set_parameter_property AvChannel DESCRIPTION ""
set_parameter_property AvChannel AFFECTS_ELABORATION true
set_parameter_property AvChannel HDL_PARAMETER false

add_parameter ChanWidth POSITIVE 1 ""
set_parameter_property ChanWidth DEFAULT_VALUE 2
set_parameter_property ChanWidth DISPLAY_NAME "Channel width"
set_parameter_property ChanWidth WIDTH ""
set_parameter_property ChanWidth TYPE INTEGER
set_parameter_property ChanWidth UNITS BITS
set_parameter_property ChanWidth ALLOWED_RANGES 1:128
set_parameter_property ChanWidth DESCRIPTION ""
set_parameter_property ChanWidth AFFECTS_GENERATION false
set_parameter_property ChanWidth HDL_PARAMETER true

add_parameter AvPacket POSITIVE 1 ""
set_parameter_property AvPacket DEFAULT_VALUE false
set_parameter_property AvPacket DISPLAY_NAME "Avalon-ST Packet"
set_parameter_property AvPacket WIDTH ""
set_parameter_property AvPacket TYPE BOOLEAN
set_parameter_property AvPacket UNITS None
set_parameter_property AvPacket DESCRIPTION ""
set_parameter_property AvPacket AFFECTS_ELABORATION true
set_parameter_property AvPacket HDL_PARAMETER false

add_parameter AvError POSITIVE 1 ""
set_parameter_property AvError DEFAULT_VALUE false
set_parameter_property AvError DISPLAY_NAME "Use error"
set_parameter_property AvError WIDTH ""
set_parameter_property AvError TYPE BOOLEAN
set_parameter_property AvError UNITS None
set_parameter_property AvError DESCRIPTION ""
set_parameter_property AvError AFFECTS_ELABORATION true
set_parameter_property AvError HDL_PARAMETER false

proc elaborate {} {
  set dps [get_parameter_value BitsPerSymbol]
  set dataw [expr [get_parameter_value BitsPerSymbol] * [get_parameter_value SymbolsPerBeat]]
  set emptyw [expr int(log([get_parameter_value SymbolsPerBeat])/log(2))]
  set chanw [get_parameter_value ChanWidth]

  add_interface out avalon_streaming start
  set_interface_property out associatedClock clk
  set_interface_property out associatedReset reset
  set_interface_property out dataBitsPerSymbol $dps
  set_interface_property out errorDescriptor ""
  set_interface_property out firstSymbolInHighOrderBits true
  set_interface_property out maxChannel 0
  set_interface_property out readyLatency 0
  set_interface_property out ENABLED true
  set_interface_property out EXPORT_OF ""
  set_interface_property out PORT_NAME_MAP ""
  set_interface_property out CMSIS_SVD_VARIABLES ""
  set_interface_property out SVD_ADDRESS_GROUP ""

  add_interface_port out out_channel channel Output $chanw
  add_interface_port out out_data data Output $dataw
  add_interface_port out out_empty empty Output $emptyw
  add_interface_port out out_error error Output 1
  add_interface_port out out_ready ready Input 1
  add_interface_port out out_valid valid Output 1
  add_interface_port out out_startofpacket startofpacket Output 1
  add_interface_port out out_endofpacket endofpacket Output 1

  add_interface in0 avalon_streaming end
  set_interface_property in0 associatedClock clk
  set_interface_property in0 associatedReset reset
  set_interface_property in0 dataBitsPerSymbol $dps
  set_interface_property in0 errorDescriptor ""
  set_interface_property in0 firstSymbolInHighOrderBits true
  set_interface_property in0 maxChannel 0
  set_interface_property in0 readyLatency 0
  set_interface_property in0 ENABLED true
  set_interface_property in0 EXPORT_OF ""
  set_interface_property in0 PORT_NAME_MAP ""
  set_interface_property in0 CMSIS_SVD_VARIABLES ""
  set_interface_property in0 SVD_ADDRESS_GROUP ""

  add_interface_port in0 in0_channel channel Input $chanw
  add_interface_port in0 in0_data data Input $dataw
  add_interface_port in0 in0_empty empty Input $emptyw
  add_interface_port in0 in0_error error Input 1
  add_interface_port in0 in0_ready ready Output 1
  add_interface_port in0 in0_valid valid Input 1
  add_interface_port in0 in0_endofpacket endofpacket Input 1
  add_interface_port in0 in0_startofpacket startofpacket Input 1

  add_interface in1 avalon_streaming end
  set_interface_property in1 associatedClock clk
  set_interface_property in1 associatedReset reset
  set_interface_property in1 dataBitsPerSymbol $dps
  set_interface_property in1 errorDescriptor ""
  set_interface_property in1 firstSymbolInHighOrderBits true
  set_interface_property in1 maxChannel 0
  set_interface_property in1 readyLatency 0
  set_interface_property in1 ENABLED true
  set_interface_property in1 EXPORT_OF ""
  set_interface_property in1 PORT_NAME_MAP ""
  set_interface_property in1 CMSIS_SVD_VARIABLES ""
  set_interface_property in1 SVD_ADDRESS_GROUP ""

  add_interface_port in1 in1_channel channel Input $chanw
  add_interface_port in1 in1_data data Input $dataw
  add_interface_port in1 in1_empty empty Input $emptyw
  add_interface_port in1 in1_error error Input 1
  add_interface_port in1 in1_ready ready Output 1
  add_interface_port in1 in1_valid valid Input 1
  add_interface_port in1 in1_endofpacket endofpacket Input 1
  add_interface_port in1 in1_startofpacket startofpacket Input 1

  if {[get_parameter_value AvError] == "false"} {
    set_port_property out_error termination true
    set_port_property in0_error termination true
    set_port_property in0_error termination_value 0
    set_port_property in1_error termination true
    set_port_property in1_error termination_value 0
  }

  if {[get_parameter_value AvChannel] == "false"} {
    set_port_property out_channel termination true
    set_port_property in0_channel termination true
    set_port_property in0_channel termination_value 0
    set_port_property in1_channel termination true
    set_port_property in1_channel termination_value 0
  }

  if {[get_parameter_value AvPacket] == "false"} {
    set_port_property out_empty         termination true
    set_port_property out_endofpacket   termination true
    set_port_property out_startofpacket termination true
    set_port_property in0_empty         termination true
    set_port_property in0_empty         termination_value 0
    set_port_property in0_endofpacket   termination true
    set_port_property in0_endofpacket   termination_value 0
    set_port_property in0_startofpacket termination true
    set_port_property in0_startofpacket termination_value 0
    set_port_property in1_empty         termination true
    set_port_property in1_empty         termination_value 0
    set_port_property in1_endofpacket   termination true
    set_port_property in1_endofpacket   termination_value 0
    set_port_property in1_startofpacket termination true
    set_port_property in1_startofpacket termination_value 0
  }
}

set_module_property ELABORATION_CALLBACK elaborate



#
# display items
#


#
# connection point clk
#
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


#
# connection point reset
#
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1

