# TCL File Generated by Component Editor 18.1
# Sun Sep 29 12:04:03 CEST 2019
# DO NOT MODIFY


# 
# fc_8g_xcvr "Fibre Chnannel 8G Transceiver" v1.0
# bluecmd 2019.09.29.12:04:03
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module fc_8g_xcvr
# 
set_module_property DESCRIPTION ""
set_module_property NAME fc_8g_xcvr
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR bluecmd
set_module_property DISPLAY_NAME "Fibre Chnannel 8G Transceiver"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL fc_8g_xcvr
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file fc_8g_xcvr.sv VERILOG PATH fc_8g_xcvr.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point tx
# 
add_interface tx avalon_streaming end
set_interface_property tx associatedClock clk
set_interface_property tx associatedReset reset
set_interface_property tx dataBitsPerSymbol 8
set_interface_property tx errorDescriptor ""
set_interface_property tx firstSymbolInHighOrderBits true
set_interface_property tx maxChannel 0
set_interface_property tx readyLatency 0
set_interface_property tx ENABLED true
set_interface_property tx EXPORT_OF ""
set_interface_property tx PORT_NAME_MAP ""
set_interface_property tx CMSIS_SVD_VARIABLES ""
set_interface_property tx SVD_ADDRESS_GROUP ""

add_interface_port tx tx_data data Input 32
add_interface_port tx tx_ready ready Output 1


# 
# connection point rx
# 
add_interface rx avalon_streaming start
set_interface_property rx associatedClock clk
set_interface_property rx associatedReset reset
set_interface_property rx dataBitsPerSymbol 8
set_interface_property rx errorDescriptor ""
set_interface_property rx firstSymbolInHighOrderBits true
set_interface_property rx maxChannel 0
set_interface_property rx readyLatency 0
set_interface_property rx ENABLED true
set_interface_property rx EXPORT_OF ""
set_interface_property rx PORT_NAME_MAP ""
set_interface_property rx CMSIS_SVD_VARIABLES ""
set_interface_property rx SVD_ADDRESS_GROUP ""

add_interface_port rx rx_data data Output 32
add_interface_port rx rx_valid valid Output 1


# 
# connection point line_tx
# 
add_interface line_tx conduit end
set_interface_property line_tx associatedClock ""
set_interface_property line_tx associatedReset ""
set_interface_property line_tx ENABLED true
set_interface_property line_tx EXPORT_OF ""
set_interface_property line_tx PORT_NAME_MAP ""
set_interface_property line_tx CMSIS_SVD_VARIABLES ""
set_interface_property line_tx SVD_ADDRESS_GROUP ""

add_interface_port line_tx td_p lvds Output 1


# 
# connection point line_rx
# 
add_interface line_rx conduit end
set_interface_property line_rx associatedClock ""
set_interface_property line_rx associatedReset ""
set_interface_property line_rx ENABLED true
set_interface_property line_rx EXPORT_OF ""
set_interface_property line_rx PORT_NAME_MAP ""
set_interface_property line_rx CMSIS_SVD_VARIABLES ""
set_interface_property line_rx SVD_ADDRESS_GROUP ""

add_interface_port line_rx rd_p lvds Input 1


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1

