# TCL File Generated by Component Editor 19.1
# Fri Oct 18 21:59:14 CEST 2019
# DO NOT MODIFY


# 
# fc_8g_xcvr "Fibre Chnannel 8G Transceiver" v1.0
# bluecmd 2019.10.18.21:59:14
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module fc_8g_xcvr
# 
set_module_property DESCRIPTION ""
set_module_property NAME fc_8g_xcvr
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR bluecmd
set_module_property DISPLAY_NAME "Fibre Chnannel 8G Transceiver"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL fc_8g_xcvr
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file fc_8g_xcvr.sv VERILOG PATH fc_8g_xcvr.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL fc_8g_xcvr
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file fc_8g_xcvr.sv VERILOG PATH fc_8g_xcvr.sv
add_fileset_file fc_phy.v VERILOG PATH ../altera_fc_phy/fc_phy_sim/fc_phy.v
add_fileset_file altera_xcvr_functions.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/altera_xcvr_functions.sv MENTOR_SPECIFIC
add_fileset_file altera_xcvr_custom.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/altera_xcvr_custom.sv
add_fileset_file sv_xcvr_custom_nr.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/sv_xcvr_custom_nr.sv
add_fileset_file sv_xcvr_custom_native.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/sv_xcvr_custom_native.sv
add_fileset_file alt_xcvr_resync.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/alt_xcvr_resync.sv MENTOR_SPECIFIC
add_fileset_file alt_xcvr_csr_common_h.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/alt_xcvr_csr_common_h.sv MENTOR_SPECIFIC
add_fileset_file alt_xcvr_csr_common.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/alt_xcvr_csr_common.sv MENTOR_SPECIFIC
add_fileset_file alt_xcvr_csr_pcs8g_h.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/alt_xcvr_csr_pcs8g_h.sv MENTOR_SPECIFIC
add_fileset_file alt_xcvr_csr_pcs8g.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/alt_xcvr_csr_pcs8g.sv MENTOR_SPECIFIC
add_fileset_file alt_xcvr_csr_selector.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/alt_xcvr_csr_selector.sv MENTOR_SPECIFIC
add_fileset_file alt_xcvr_mgmt2dec.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/alt_xcvr_mgmt2dec.sv MENTOR_SPECIFIC
add_fileset_file altera_wait_generate.v VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/altera_wait_generate.v MENTOR_SPECIFIC
add_fileset_file sv_pcs.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/sv_pcs.sv MENTOR_SPECIFIC
add_fileset_file sv_pcs_ch.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/sv_pcs_ch.sv MENTOR_SPECIFIC
add_fileset_file sv_pma.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/sv_pma.sv MENTOR_SPECIFIC
add_fileset_file sv_reconfig_bundle_to_xcvr.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/sv_reconfig_bundle_to_xcvr.sv MENTOR_SPECIFIC
add_fileset_file sv_reconfig_bundle_to_ip.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/sv_reconfig_bundle_to_ip.sv MENTOR_SPECIFIC
add_fileset_file sv_reconfig_bundle_merger.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/sv_reconfig_bundle_merger.sv MENTOR_SPECIFIC
add_fileset_file sv_rx_pma.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/sv_rx_pma.sv MENTOR_SPECIFIC
add_fileset_file sv_tx_pma.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/sv_tx_pma.sv MENTOR_SPECIFIC
add_fileset_file sv_tx_pma_ch.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/sv_tx_pma_ch.sv MENTOR_SPECIFIC
add_fileset_file sv_xcvr_h.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/sv_xcvr_h.sv MENTOR_SPECIFIC
add_fileset_file sv_xcvr_avmm_csr.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/sv_xcvr_avmm_csr.sv MENTOR_SPECIFIC
add_fileset_file sv_xcvr_avmm_dcd.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/sv_xcvr_avmm_dcd.sv MENTOR_SPECIFIC
add_fileset_file sv_xcvr_avmm.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/sv_xcvr_avmm.sv MENTOR_SPECIFIC
add_fileset_file sv_xcvr_data_adapter.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/sv_xcvr_data_adapter.sv MENTOR_SPECIFIC
add_fileset_file sv_xcvr_native.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/sv_xcvr_native.sv MENTOR_SPECIFIC
add_fileset_file sv_xcvr_plls.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/sv_xcvr_plls.sv MENTOR_SPECIFIC
add_fileset_file sv_hssi_10g_rx_pcs_rbc.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/sv_hssi_10g_rx_pcs_rbc.sv MENTOR_SPECIFIC
add_fileset_file sv_hssi_10g_tx_pcs_rbc.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/sv_hssi_10g_tx_pcs_rbc.sv MENTOR_SPECIFIC
add_fileset_file sv_hssi_8g_rx_pcs_rbc.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/sv_hssi_8g_rx_pcs_rbc.sv MENTOR_SPECIFIC
add_fileset_file sv_hssi_8g_tx_pcs_rbc.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/sv_hssi_8g_tx_pcs_rbc.sv MENTOR_SPECIFIC
add_fileset_file sv_hssi_8g_pcs_aggregate_rbc.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/sv_hssi_8g_pcs_aggregate_rbc.sv MENTOR_SPECIFIC
add_fileset_file sv_hssi_common_pcs_pma_interface_rbc.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/sv_hssi_common_pcs_pma_interface_rbc.sv MENTOR_SPECIFIC
add_fileset_file sv_hssi_common_pld_pcs_interface_rbc.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/sv_hssi_common_pld_pcs_interface_rbc.sv MENTOR_SPECIFIC
add_fileset_file sv_hssi_pipe_gen1_2_rbc.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/sv_hssi_pipe_gen1_2_rbc.sv MENTOR_SPECIFIC
add_fileset_file sv_hssi_pipe_gen3_rbc.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/sv_hssi_pipe_gen3_rbc.sv MENTOR_SPECIFIC
add_fileset_file sv_hssi_rx_pcs_pma_interface_rbc.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/sv_hssi_rx_pcs_pma_interface_rbc.sv MENTOR_SPECIFIC
add_fileset_file sv_hssi_rx_pld_pcs_interface_rbc.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/sv_hssi_rx_pld_pcs_interface_rbc.sv MENTOR_SPECIFIC
add_fileset_file sv_hssi_tx_pcs_pma_interface_rbc.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/sv_hssi_tx_pcs_pma_interface_rbc.sv MENTOR_SPECIFIC
add_fileset_file sv_hssi_tx_pld_pcs_interface_rbc.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/sv_hssi_tx_pld_pcs_interface_rbc.sv MENTOR_SPECIFIC
add_fileset_file altera_xcvr_reset_control.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/altera_xcvr_reset_control.sv MENTOR_SPECIFIC
add_fileset_file alt_xcvr_reset_counter.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/alt_xcvr_reset_counter.sv MENTOR_SPECIFIC
add_fileset_file alt_xcvr_arbiter.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/alt_xcvr_arbiter.sv MENTOR_SPECIFIC
add_fileset_file alt_xcvr_m2s.sv VERILOG PATH ../altera_fc_phy/fc_phy_sim/altera_xcvr_custom_phy/mentor/alt_xcvr_m2s.sv MENTOR_SPECIFIC


# 
# parameters
# 


# 
# display items
# 


# 
# connection point tx
# 
add_interface tx avalon_streaming end
set_interface_property tx associatedClock tx_clk
set_interface_property tx associatedReset reset
set_interface_property tx dataBitsPerSymbol 8
set_interface_property tx errorDescriptor ""
set_interface_property tx firstSymbolInHighOrderBits true
set_interface_property tx maxChannel 0
set_interface_property tx readyLatency 0
set_interface_property tx ENABLED true
set_interface_property tx EXPORT_OF ""
set_interface_property tx PORT_NAME_MAP ""
set_interface_property tx CMSIS_SVD_VARIABLES ""
set_interface_property tx SVD_ADDRESS_GROUP ""

add_interface_port tx tx_data data Input 32
add_interface_port tx tx_ready ready Output 1


# 
# connection point rx
# 
add_interface rx avalon_streaming start
set_interface_property rx associatedClock rx_clk
set_interface_property rx associatedReset reset
set_interface_property rx dataBitsPerSymbol 8
set_interface_property rx errorDescriptor ""
set_interface_property rx firstSymbolInHighOrderBits true
set_interface_property rx maxChannel 0
set_interface_property rx readyLatency 0
set_interface_property rx ENABLED true
set_interface_property rx EXPORT_OF ""
set_interface_property rx PORT_NAME_MAP ""
set_interface_property rx CMSIS_SVD_VARIABLES ""
set_interface_property rx SVD_ADDRESS_GROUP ""

add_interface_port rx rx_data data Output 32
add_interface_port rx rx_valid valid Output 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock mgmt_clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point mgmt_clk
# 
add_interface mgmt_clk clock end
set_interface_property mgmt_clk clockRate 0
set_interface_property mgmt_clk ENABLED true
set_interface_property mgmt_clk EXPORT_OF ""
set_interface_property mgmt_clk PORT_NAME_MAP ""
set_interface_property mgmt_clk CMSIS_SVD_VARIABLES ""
set_interface_property mgmt_clk SVD_ADDRESS_GROUP ""

add_interface_port mgmt_clk mgmt_clk clk Input 1


# 
# connection point mgmt_mm
# 
add_interface mgmt_mm avalon end
set_interface_property mgmt_mm addressUnits WORDS
set_interface_property mgmt_mm associatedClock mgmt_clk
set_interface_property mgmt_mm associatedReset reset
set_interface_property mgmt_mm bitsPerSymbol 8
set_interface_property mgmt_mm burstOnBurstBoundariesOnly false
set_interface_property mgmt_mm burstcountUnits WORDS
set_interface_property mgmt_mm explicitAddressSpan 0
set_interface_property mgmt_mm holdTime 0
set_interface_property mgmt_mm linewrapBursts false
set_interface_property mgmt_mm maximumPendingReadTransactions 0
set_interface_property mgmt_mm maximumPendingWriteTransactions 0
set_interface_property mgmt_mm readLatency 0
set_interface_property mgmt_mm readWaitTime 1
set_interface_property mgmt_mm setupTime 0
set_interface_property mgmt_mm timingUnits Cycles
set_interface_property mgmt_mm writeWaitTime 0
set_interface_property mgmt_mm ENABLED true
set_interface_property mgmt_mm EXPORT_OF ""
set_interface_property mgmt_mm PORT_NAME_MAP ""
set_interface_property mgmt_mm CMSIS_SVD_VARIABLES ""
set_interface_property mgmt_mm SVD_ADDRESS_GROUP ""

add_interface_port mgmt_mm mm_address address Input 10
add_interface_port mgmt_mm mm_waitrequest waitrequest Output 1
add_interface_port mgmt_mm mm_read read Input 1
add_interface_port mgmt_mm mm_write write Input 1
add_interface_port mgmt_mm mm_readdata readdata Output 32
add_interface_port mgmt_mm mm_writedata writedata Input 32
set_interface_assignment mgmt_mm embeddedsw.configuration.isFlash 0
set_interface_assignment mgmt_mm embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment mgmt_mm embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment mgmt_mm embeddedsw.configuration.isPrintableDevice 0


# 
# connection point tx_clk
# 
add_interface tx_clk clock start
set_interface_property tx_clk associatedDirectClock ""
set_interface_property tx_clk clockRate 0
set_interface_property tx_clk clockRateKnown false
set_interface_property tx_clk ENABLED true
set_interface_property tx_clk EXPORT_OF ""
set_interface_property tx_clk PORT_NAME_MAP ""
set_interface_property tx_clk CMSIS_SVD_VARIABLES ""
set_interface_property tx_clk SVD_ADDRESS_GROUP ""

add_interface_port tx_clk tx_clk clk Output 1


# 
# connection point rx_clk
# 
add_interface rx_clk clock start
set_interface_property rx_clk associatedDirectClock ""
set_interface_property rx_clk clockRate 0
set_interface_property rx_clk clockRateKnown false
set_interface_property rx_clk ENABLED true
set_interface_property rx_clk EXPORT_OF ""
set_interface_property rx_clk PORT_NAME_MAP ""
set_interface_property rx_clk CMSIS_SVD_VARIABLES ""
set_interface_property rx_clk SVD_ADDRESS_GROUP ""

add_interface_port rx_clk rx_clk clk Output 1


# 
# connection point line_td
# 
add_interface line_td conduit end
set_interface_property line_td associatedClock ""
set_interface_property line_td associatedReset ""
set_interface_property line_td ENABLED true
set_interface_property line_td EXPORT_OF ""
set_interface_property line_td PORT_NAME_MAP ""
set_interface_property line_td CMSIS_SVD_VARIABLES ""
set_interface_property line_td SVD_ADDRESS_GROUP ""

add_interface_port line_td td_p lvds Output 1


# 
# connection point line_rd
# 
add_interface line_rd conduit end
set_interface_property line_rd associatedClock ""
set_interface_property line_rd associatedReset ""
set_interface_property line_rd ENABLED true
set_interface_property line_rd EXPORT_OF ""
set_interface_property line_rd PORT_NAME_MAP ""
set_interface_property line_rd CMSIS_SVD_VARIABLES ""
set_interface_property line_rd SVD_ADDRESS_GROUP ""

add_interface_port line_rd rd_p lvds Input 1


# 
# connection point reconfig_from_xcvr
# 
add_interface reconfig_from_xcvr conduit end
set_interface_property reconfig_from_xcvr associatedClock ""
set_interface_property reconfig_from_xcvr associatedReset ""
set_interface_property reconfig_from_xcvr ENABLED true
set_interface_property reconfig_from_xcvr EXPORT_OF ""
set_interface_property reconfig_from_xcvr PORT_NAME_MAP ""
set_interface_property reconfig_from_xcvr CMSIS_SVD_VARIABLES ""
set_interface_property reconfig_from_xcvr SVD_ADDRESS_GROUP ""

add_interface_port reconfig_from_xcvr reconfig_from_xcvr reconfig_from_xcvr Output 92


# 
# connection point reconfig_to_xcvr
# 
add_interface reconfig_to_xcvr conduit end
set_interface_property reconfig_to_xcvr associatedClock ""
set_interface_property reconfig_to_xcvr associatedReset ""
set_interface_property reconfig_to_xcvr ENABLED true
set_interface_property reconfig_to_xcvr EXPORT_OF ""
set_interface_property reconfig_to_xcvr PORT_NAME_MAP ""
set_interface_property reconfig_to_xcvr CMSIS_SVD_VARIABLES ""
set_interface_property reconfig_to_xcvr SVD_ADDRESS_GROUP ""

add_interface_port reconfig_to_xcvr reconfig_to_xcvr reconfig_to_xcvr Input 140


# 
# connection point phy_clk
# 
add_interface phy_clk clock end
set_interface_property phy_clk clockRate 0
set_interface_property phy_clk ENABLED true
set_interface_property phy_clk EXPORT_OF ""
set_interface_property phy_clk PORT_NAME_MAP ""
set_interface_property phy_clk CMSIS_SVD_VARIABLES ""
set_interface_property phy_clk SVD_ADDRESS_GROUP ""

add_interface_port phy_clk phy_clk clk Input 1

