# TCL File Generated by Component Editor 20.1
# Thu Aug 20 19:38:23 CEST 2020
# DO NOT MODIFY


# 
# intel_pcie_status "Intel PCIe Status" v1.0
#  2020.08.20.19:38:23
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module intel_pcie_status
# 
set_module_property DESCRIPTION ""
set_module_property NAME intel_pcie_status
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Intel PCIe Status"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL intel_pcie_status
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file intel_pcie_status.sv SYSTEM_VERILOG PATH intel_pcie_status.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL intel_pcie_status
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file intel_pcie_status.sv SYSTEM_VERILOG PATH intel_pcie_status.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point hip_status_drv
# 
add_interface hip_status_drv conduit end
set_interface_property hip_status_drv associatedClock ""
set_interface_property hip_status_drv associatedReset ""
set_interface_property hip_status_drv ENABLED true
set_interface_property hip_status_drv EXPORT_OF ""
set_interface_property hip_status_drv PORT_NAME_MAP ""
set_interface_property hip_status_drv CMSIS_SVD_VARIABLES ""
set_interface_property hip_status_drv SVD_ADDRESS_GROUP ""

add_interface_port hip_status_drv derr_cor_ext_rcv_drv derr_cor_ext_rcv Input 1
add_interface_port hip_status_drv derr_cor_ext_rpl_drv derr_cor_ext_rpl Input 1
add_interface_port hip_status_drv derr_rpl_drv derr_rpl Input 1
add_interface_port hip_status_drv dlup_exit_drv dlup_exit Input 1
add_interface_port hip_status_drv ev128ns_drv ev128ns Input 1
add_interface_port hip_status_drv ev1us_drv ev1us Input 1
add_interface_port hip_status_drv hotrst_exit_drv hotrst_exit Input 1
add_interface_port hip_status_drv int_status_drv int_status Input 4
add_interface_port hip_status_drv l2_exit_drv l2_exit Input 1
add_interface_port hip_status_drv lane_act_drv lane_act Input 4
add_interface_port hip_status_drv ltssmstate_drv ltssmstate Input 5
add_interface_port hip_status_drv dlup_drv dlup Input 1
add_interface_port hip_status_drv rx_par_err_drv rx_par_err Input 1
add_interface_port hip_status_drv tx_par_err_drv tx_par_err Input 2
add_interface_port hip_status_drv cfg_par_err_drv cfg_par_err Input 1
add_interface_port hip_status_drv ko_cpl_spc_header_drv ko_cpl_spc_header Input 8
add_interface_port hip_status_drv ko_cpl_spc_data_drv ko_cpl_spc_data Input 12


# 
# connection point hip_status_out
# 
add_interface hip_status_out conduit end
set_interface_property hip_status_out associatedClock ""
set_interface_property hip_status_out associatedReset ""
set_interface_property hip_status_out ENABLED true
set_interface_property hip_status_out EXPORT_OF ""
set_interface_property hip_status_out PORT_NAME_MAP ""
set_interface_property hip_status_out CMSIS_SVD_VARIABLES ""
set_interface_property hip_status_out SVD_ADDRESS_GROUP ""

add_interface_port hip_status_out derr_cor_ext_rcv_out derr_cor_ext_rcv Output 1
add_interface_port hip_status_out derr_cor_ext_rpl_out derr_cor_ext_rpl Output 1
add_interface_port hip_status_out derr_rpl_out derr_rpl Output 1
add_interface_port hip_status_out dlup_exit_out dlup_exit Output 1
add_interface_port hip_status_out ev128ns_out ev128ns Output 1
add_interface_port hip_status_out ev1us_out ev1us Output 1
add_interface_port hip_status_out hotrst_exit_out hotrst_exit Output 1
add_interface_port hip_status_out int_status_out int_status Output 4
add_interface_port hip_status_out l2_exit_out l2_exit Output 1
add_interface_port hip_status_out lane_act_out lane_act Output 4
add_interface_port hip_status_out ltssmstate_out ltssmstate Output 5
add_interface_port hip_status_out dlup_out dlup Output 1
add_interface_port hip_status_out rx_par_err_out rx_par_err Output 1
add_interface_port hip_status_out tx_par_err_out tx_par_err Output 2
add_interface_port hip_status_out cfg_par_err_out cfg_par_err Output 1
add_interface_port hip_status_out ko_cpl_spc_header_out ko_cpl_spc_header Output 8
add_interface_port hip_status_out ko_cpl_spc_data_out ko_cpl_spc_data Output 12


# 
# connection point mm
# 
add_interface mm avalon end
set_interface_property mm addressUnits WORDS
set_interface_property mm associatedClock clk
set_interface_property mm associatedReset reset
set_interface_property mm bitsPerSymbol 8
set_interface_property mm burstOnBurstBoundariesOnly false
set_interface_property mm burstcountUnits WORDS
set_interface_property mm explicitAddressSpan 0
set_interface_property mm holdTime 0
set_interface_property mm linewrapBursts false
set_interface_property mm maximumPendingReadTransactions 0
set_interface_property mm maximumPendingWriteTransactions 0
set_interface_property mm readLatency 0
set_interface_property mm readWaitTime 1
set_interface_property mm setupTime 0
set_interface_property mm timingUnits Cycles
set_interface_property mm writeWaitTime 0
set_interface_property mm ENABLED true
set_interface_property mm EXPORT_OF ""
set_interface_property mm PORT_NAME_MAP ""
set_interface_property mm CMSIS_SVD_VARIABLES ""
set_interface_property mm SVD_ADDRESS_GROUP ""

add_interface_port mm mm_address address Input 4
add_interface_port mm mm_readdata readdata Output 32
add_interface_port mm mm_read read Input 1
set_interface_assignment mm embeddedsw.configuration.isFlash 0
set_interface_assignment mm embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment mm embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment mm embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1

