# TCL File Generated by Component Editor 20.1
# Wed Sep 09 17:36:25 CEST 2020
# DO NOT MODIFY


# 
# fc_framer "Fibre Channel Framer" v1.0
# bluecmd 2020.09.09.17:36:25
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module fc_framer
# 
set_module_property DESCRIPTION ""
set_module_property NAME fc_framer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR bluecmd
set_module_property DISPLAY_NAME "Fibre Channel Framer"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL fc_framer
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file fc.sv SYSTEM_VERILOG PATH ../fc.sv
add_fileset_file fc_state_rx.sv SYSTEM_VERILOG PATH fc_state_rx.sv
add_fileset_file fc_state_tx.sv SYSTEM_VERILOG PATH fc_state_tx.sv
add_fileset_file fc_framer.sv SYSTEM_VERILOG PATH fc_framer.sv
add_fileset_file fc_framer.sdc SDC PATH fc_framer.sdc

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL fc_framer
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file fc.sv SYSTEM_VERILOG PATH ../fc.sv
add_fileset_file fc_state_rx.sv SYSTEM_VERILOG PATH fc_state_rx.sv
add_fileset_file fc_state_tx.sv SYSTEM_VERILOG PATH fc_state_tx.sv
add_fileset_file fc_framer.sv SYSTEM_VERILOG PATH fc_framer.sv


# 
# parameters
# 
add_parameter OL1_DELAY_US POSITIVE 5000 ""
set_parameter_property OL1_DELAY_US DEFAULT_VALUE 5000
set_parameter_property OL1_DELAY_US DISPLAY_NAME "Time delay in OL1 state"
set_parameter_property OL1_DELAY_US WIDTH ""
set_parameter_property OL1_DELAY_US TYPE POSITIVE
set_parameter_property OL1_DELAY_US UNITS MICROSECONDS
set_parameter_property OL1_DELAY_US ALLOWED_RANGES 0:1000000
set_parameter_property OL1_DELAY_US DESCRIPTION ""
set_parameter_property OL1_DELAY_US AFFECTS_GENERATION false
set_parameter_property OL1_DELAY_US HDL_PARAMETER true
add_parameter MTU POSITIVE 3072 ""
set_parameter_property MTU DEFAULT_VALUE 3072
set_parameter_property MTU DISPLAY_NAME "FC Frame MTU"
set_parameter_property MTU WIDTH ""
set_parameter_property MTU TYPE POSITIVE
set_parameter_property MTU UNITS None
set_parameter_property MTU ALLOWED_RANGES 8:4064
set_parameter_property MTU DESCRIPTION ""
set_parameter_property MTU AFFECTS_GENERATION false
set_parameter_property MTU HDL_PARAMETER true
add_parameter WAIT_FOR_PEER BOOLEAN false ""
set_parameter_property WAIT_FOR_PEER DEFAULT_VALUE false
set_parameter_property WAIT_FOR_PEER DISPLAY_NAME "Wait for peer port to stabilize before activating"
set_parameter_property WAIT_FOR_PEER WIDTH ""
set_parameter_property WAIT_FOR_PEER TYPE BOOLEAN
set_parameter_property WAIT_FOR_PEER UNITS None
set_parameter_property WAIT_FOR_PEER DESCRIPTION ""
set_parameter_property WAIT_FOR_PEER AFFECTS_ELABORATION false
set_parameter_property WAIT_FOR_PEER HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock ""
set_interface_property reset synchronousEdges NONE
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point rx_mgmt_mm
# 
add_interface rx_mgmt_mm avalon end
set_interface_property rx_mgmt_mm addressUnits WORDS
set_interface_property rx_mgmt_mm associatedClock rx_clk
set_interface_property rx_mgmt_mm associatedReset reset
set_interface_property rx_mgmt_mm bitsPerSymbol 8
set_interface_property rx_mgmt_mm burstOnBurstBoundariesOnly false
set_interface_property rx_mgmt_mm burstcountUnits WORDS
set_interface_property rx_mgmt_mm explicitAddressSpan 0
set_interface_property rx_mgmt_mm holdTime 0
set_interface_property rx_mgmt_mm linewrapBursts false
set_interface_property rx_mgmt_mm maximumPendingReadTransactions 0
set_interface_property rx_mgmt_mm maximumPendingWriteTransactions 0
set_interface_property rx_mgmt_mm readLatency 0
set_interface_property rx_mgmt_mm readWaitTime 1
set_interface_property rx_mgmt_mm setupTime 0
set_interface_property rx_mgmt_mm timingUnits Cycles
set_interface_property rx_mgmt_mm writeWaitTime 0
set_interface_property rx_mgmt_mm ENABLED true
set_interface_property rx_mgmt_mm EXPORT_OF ""
set_interface_property rx_mgmt_mm PORT_NAME_MAP ""
set_interface_property rx_mgmt_mm CMSIS_SVD_VARIABLES ""
set_interface_property rx_mgmt_mm SVD_ADDRESS_GROUP ""

add_interface_port rx_mgmt_mm rx_mm_address address Input 3
add_interface_port rx_mgmt_mm rx_mm_read read Input 1
add_interface_port rx_mgmt_mm rx_mm_readdata readdata Output 32
set_interface_assignment rx_mgmt_mm embeddedsw.configuration.isFlash 0
set_interface_assignment rx_mgmt_mm embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment rx_mgmt_mm embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment rx_mgmt_mm embeddedsw.configuration.isPrintableDevice 0


# 
# connection point tx_mgmt_mm
# 
add_interface tx_mgmt_mm avalon end
set_interface_property tx_mgmt_mm addressUnits WORDS
set_interface_property tx_mgmt_mm associatedClock tx_clk
set_interface_property tx_mgmt_mm associatedReset reset
set_interface_property tx_mgmt_mm bitsPerSymbol 8
set_interface_property tx_mgmt_mm burstOnBurstBoundariesOnly false
set_interface_property tx_mgmt_mm burstcountUnits WORDS
set_interface_property tx_mgmt_mm explicitAddressSpan 0
set_interface_property tx_mgmt_mm holdTime 0
set_interface_property tx_mgmt_mm linewrapBursts false
set_interface_property tx_mgmt_mm maximumPendingReadTransactions 0
set_interface_property tx_mgmt_mm maximumPendingWriteTransactions 0
set_interface_property tx_mgmt_mm readLatency 0
set_interface_property tx_mgmt_mm readWaitTime 1
set_interface_property tx_mgmt_mm setupTime 0
set_interface_property tx_mgmt_mm timingUnits Cycles
set_interface_property tx_mgmt_mm writeWaitTime 0
set_interface_property tx_mgmt_mm ENABLED true
set_interface_property tx_mgmt_mm EXPORT_OF ""
set_interface_property tx_mgmt_mm PORT_NAME_MAP ""
set_interface_property tx_mgmt_mm CMSIS_SVD_VARIABLES ""
set_interface_property tx_mgmt_mm SVD_ADDRESS_GROUP ""

add_interface_port tx_mgmt_mm tx_mm_address address Input 3
add_interface_port tx_mgmt_mm tx_mm_read read Input 1
add_interface_port tx_mgmt_mm tx_mm_readdata readdata Output 32
set_interface_assignment tx_mgmt_mm embeddedsw.configuration.isFlash 0
set_interface_assignment tx_mgmt_mm embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment tx_mgmt_mm embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment tx_mgmt_mm embeddedsw.configuration.isPrintableDevice 0


# 
# connection point tx_clk
# 
add_interface tx_clk clock end
set_interface_property tx_clk clockRate 0
set_interface_property tx_clk ENABLED true
set_interface_property tx_clk EXPORT_OF ""
set_interface_property tx_clk PORT_NAME_MAP ""
set_interface_property tx_clk CMSIS_SVD_VARIABLES ""
set_interface_property tx_clk SVD_ADDRESS_GROUP ""

add_interface_port tx_clk tx_clk clk Input 1


# 
# connection point rx_clk
# 
add_interface rx_clk clock end
set_interface_property rx_clk clockRate 0
set_interface_property rx_clk ENABLED true
set_interface_property rx_clk EXPORT_OF ""
set_interface_property rx_clk PORT_NAME_MAP ""
set_interface_property rx_clk CMSIS_SVD_VARIABLES ""
set_interface_property rx_clk SVD_ADDRESS_GROUP ""

add_interface_port rx_clk rx_clk clk Input 1


# 
# connection point userrx
# 
add_interface userrx avalon_streaming start
set_interface_property userrx associatedClock rx_clk
set_interface_property userrx associatedReset reset
set_interface_property userrx dataBitsPerSymbol 8
set_interface_property userrx errorDescriptor ""
set_interface_property userrx firstSymbolInHighOrderBits true
set_interface_property userrx maxChannel 0
set_interface_property userrx readyLatency 0
set_interface_property userrx ENABLED true
set_interface_property userrx EXPORT_OF ""
set_interface_property userrx PORT_NAME_MAP ""
set_interface_property userrx CMSIS_SVD_VARIABLES ""
set_interface_property userrx SVD_ADDRESS_GROUP ""

add_interface_port userrx userrx_data data Output 32
add_interface_port userrx userrx_empty empty Output 2
add_interface_port userrx userrx_valid valid Output 1
add_interface_port userrx userrx_endofpacket endofpacket Output 1
add_interface_port userrx userrx_startofpacket startofpacket Output 1


# 
# connection point usertx
# 
add_interface usertx avalon_streaming end
set_interface_property usertx associatedClock tx_clk
set_interface_property usertx associatedReset reset
set_interface_property usertx dataBitsPerSymbol 8
set_interface_property usertx errorDescriptor ""
set_interface_property usertx firstSymbolInHighOrderBits true
set_interface_property usertx maxChannel 0
set_interface_property usertx readyLatency 0
set_interface_property usertx ENABLED true
set_interface_property usertx EXPORT_OF ""
set_interface_property usertx PORT_NAME_MAP ""
set_interface_property usertx CMSIS_SVD_VARIABLES ""
set_interface_property usertx SVD_ADDRESS_GROUP ""

add_interface_port usertx usertx_data data Input 32
add_interface_port usertx usertx_valid valid Input 1
add_interface_port usertx usertx_ready ready Output 1
add_interface_port usertx usertx_endofpacket endofpacket Input 1
add_interface_port usertx usertx_startofpacket startofpacket Input 1


# 
# connection point avtx
# 
add_interface avtx avalon_streaming start
set_interface_property avtx associatedClock tx_clk
set_interface_property avtx associatedReset reset
set_interface_property avtx dataBitsPerSymbol 9
set_interface_property avtx errorDescriptor ""
set_interface_property avtx firstSymbolInHighOrderBits true
set_interface_property avtx maxChannel 0
set_interface_property avtx readyLatency 0
set_interface_property avtx ENABLED true
set_interface_property avtx EXPORT_OF ""
set_interface_property avtx PORT_NAME_MAP ""
set_interface_property avtx CMSIS_SVD_VARIABLES ""
set_interface_property avtx SVD_ADDRESS_GROUP ""

add_interface_port avtx avtx_data data Output 36
add_interface_port avtx avtx_ready ready Input 1
add_interface_port avtx avtx_valid valid Output 1


# 
# connection point avrx
# 
add_interface avrx avalon_streaming end
set_interface_property avrx associatedClock rx_clk
set_interface_property avrx associatedReset reset
set_interface_property avrx dataBitsPerSymbol 9
set_interface_property avrx errorDescriptor ""
set_interface_property avrx firstSymbolInHighOrderBits true
set_interface_property avrx maxChannel 0
set_interface_property avrx readyLatency 0
set_interface_property avrx ENABLED true
set_interface_property avrx EXPORT_OF ""
set_interface_property avrx PORT_NAME_MAP ""
set_interface_property avrx CMSIS_SVD_VARIABLES ""
set_interface_property avrx SVD_ADDRESS_GROUP ""

add_interface_port avrx avrx_data data Input 36
add_interface_port avrx avrx_valid valid Input 1


# 
# connection point active
# 
add_interface active conduit end
set_interface_property active associatedClock ""
set_interface_property active associatedReset ""
set_interface_property active ENABLED true
set_interface_property active EXPORT_OF ""
set_interface_property active PORT_NAME_MAP ""
set_interface_property active CMSIS_SVD_VARIABLES ""
set_interface_property active SVD_ADDRESS_GROUP ""

add_interface_port active active active Output 1


# 
# connection point peer_ready
# 
add_interface peer_ready conduit end
set_interface_property peer_ready associatedClock ""
set_interface_property peer_ready associatedReset ""
set_interface_property peer_ready ENABLED true
set_interface_property peer_ready EXPORT_OF ""
set_interface_property peer_ready PORT_NAME_MAP ""
set_interface_property peer_ready CMSIS_SVD_VARIABLES ""
set_interface_property peer_ready SVD_ADDRESS_GROUP ""

add_interface_port peer_ready peer_ready ready Input 1


# 
# connection point port_ready
# 
add_interface port_ready conduit end
set_interface_property port_ready associatedClock ""
set_interface_property port_ready associatedReset ""
set_interface_property port_ready ENABLED true
set_interface_property port_ready EXPORT_OF ""
set_interface_property port_ready PORT_NAME_MAP ""
set_interface_property port_ready CMSIS_SVD_VARIABLES ""
set_interface_property port_ready SVD_ADDRESS_GROUP ""

add_interface_port port_ready port_ready ready Output 1

