# TCL File Generated by Component Editor 20.1
# Sun Sep 13 20:03:25 CEST 2020
# DO NOT MODIFY


# 
# rs422_ctrl "RS422 Pin Controller" v1.0
#  2020.09.13.20:03:25
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module rs422_ctrl
# 
set_module_property DESCRIPTION ""
set_module_property NAME rs422_ctrl
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "RS422 Pin Controller"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL rs422_ctrl
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file rs422_ctrl.sv SYSTEM_VERILOG PATH rs422_ctrl.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL rs422_ctrl
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file rs422_ctrl.sv SYSTEM_VERILOG PATH rs422_ctrl.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point rs422
# 
add_interface rs422 conduit end
set_interface_property rs422 associatedClock clk
set_interface_property rs422 associatedReset reset
set_interface_property rs422 ENABLED true
set_interface_property rs422 EXPORT_OF ""
set_interface_property rs422 PORT_NAME_MAP ""
set_interface_property rs422 CMSIS_SVD_VARIABLES ""
set_interface_property rs422 SVD_ADDRESS_GROUP ""

add_interface_port rs422 rs422_re_n re_n Output 1
add_interface_port rs422 rs422_de de Output 1
add_interface_port rs422 rs422_te te Output 1

