name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Check
    # Grab a newer Verilator than 18.04
    runs-on: ubuntu-20.04
    steps:
    - name: Install simulators
      run: sudo apt-get install iverilog verilator python3-pip
    - name: Install cocotb
      run: |
        pip3 install cocotb
        echo "::add-path::${HOME}/.local/bin"
    - name: Check out code
      uses: actions/checkout@v2
      with:
        path: main
    - name: Check out non-free
      uses: actions/checkout@v2
      with:
        repository: bluecmd/fejkon-non-free
        token: ${{ secrets.BOT_PAT }}
        path: non-free
    - name: Test
      run: |
        export QPATH="${PWD}/non-free/quartus/"
        cd main
        ./utils/presubmit-test.sh
