name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Check
    # Grab a newer Verilator than 18.04
    runs-on: ubuntu-20.04
    steps:
    - name: Install simulators
      run: sudo apt-get install iverilog verilator
    - name: Check out code
      uses: actions/checkout@v2
    - name: Test
      run: ./utils/presubmit-test.sh
